### ISSUE TITLE
Inquiry About CUDA Memory Issue on LLFF Leaves Scene

### ISSUE THREAD

**Issue by husenlan** [iCVTEAM/IPSM#2]
Hello,wang!
I'm currently working on reproducing your impressive work on IPSM. While I've successfully trained 7 scenes from the LLFF dataset, ​​the "leaves" scene fails with a CUDA memory error​​ under identical settings. Specifically:

​​Error occurs at ~iteration 1700​​: RuntimeError: CUDA out of memory
​​Other scenes​​ (e.g., fern, orchids) ​​complete training normally​​ with the same configuration.

Have you observed similar memory issues with specific scenes like "leaves", and are there recommended adjustments for such cases?

Thank you for your time and guidance. Looking forward to your insights

**Comment by wang-qisen** [comment]
Hello, husenlan.

I'm sorry that I didn't observe similar memory issues when using 24GB VRAM. Are you using 16GB of VRAM? 

The reason for this problem is probably that the number of Gaussian points is too large. You can compare the number of Gaussian points in other scenes at 1700 iterations.

One possible approach is to load the monocular depth model into another graphics card and then load the predicted results into the current graphics card, which may save some VRAM.

Have a nice day.

**Comment by husenlan** [comment]
Hello wang-qisen,

Thank you for your earlier advice! The CUDA memory issue in the "leaves" scene is now resolved. As you suggested, uncontrolled Gaussian growth during unpooling was the root cause.

The scene occasionally reached ​​9M+ Gaussians​​ (triggering OOM), but stabilized at ​​~4M​​ in successful runs.

Thank you again for your guidance!
